name: Bench

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'coq-tactician'
      - uses: actions/checkout@v2
        with:
          repository: 'coq-tactician/coq-tactician-stdlib'
          ref: 'master'
          path: 'coq-tactician-stdlib'
      - uses: coq-community/docker-coq-action@v1.1.0
        with:
          opam_file: 'coq-tactician.opam'
          coq_version: '8.12'
          ocaml_version: '4.09-flambda'
          custom_script: |
            startGroup Print opam config
              opam config list; opam repo list; opam list
            endGroup
            startGroup Build dependencies
              opam repo add tactician git+https://github.com/coq-tactician/tmp-archive.git#dev
              opam pin add -n -y -k path coq-tactician coq-tactician/
              opam update -y
              opam install -y -j 2 coq-tactician
            endGroup
            startGroup Build
              sudo chmod -R 777 .
              opam exec -- make -C coq-tactician-stdlib -j2 BENCHMARK=2
            endGroup
            startGroup Uninstallation test
              opam remove coq-tactician-stdlib
            endGroup
